spring.application.name=Vaultiq

# ── Database ──
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultiq
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ── JWT ──
jwt.secret=${JWT_SECRET:dkFVTFRJUV9TRUNSRVRfS0VZXzI1Nl9CSVRTX01JTklNVU1fRk9SX0hNQUNfU0hBMjU2X0FMR09SSVRITQ==}
jwt.expiration=86400000

# ── Scheduling ──
spring.task.scheduling.pool.size=5